title: EUI Comparative Politics Seminar Series
#logo: /assets/img/LOGO-EUI.png
description: 
"Previous events:"
[Fall 2023](https://cpss-eui.github.io/old_events.html)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
