title: EUI Comparative Politics Seminar Series
#logo: /assets/img/LOGO-EUI.png
description: #The Comparative Politics Seminar Series in the Department of Political and Social Sciences at the European University Institute is a venue for the presentation of work in progress by scholars from across the subfield of comparative politics. 
#The series is organized by [Elias Dinas](https://www.eui.eu/people?id=elias-dinas), [Miriam Golden](https://www.miriamgolden.com/), [Simon Hix](https://simonhix.com//), and [Filip Kostelka](https://filipkostelka.com/), with support by [Daniel Urquijo](https://www.eui.eu/people?id=daniel-urquijo) and [Pau Grau](https://paugrau.cat/).
#The Comparative Politics Seminar Series is held on Thursdays during term time from "17:00" to "18:30". It takes place at Badia Fiesolana, EUI. See below for the exact location for each meeting. The event is in-person and on-line. Registration is required for online attendance. Attendance is generally restricted to members of the EUI community.

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
